# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-07 11:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='Buyers',
        ),
        migrations.RemoveField(
            model_name='e_book',
            name='Buyers',
        ),
        migrations.RemoveField(
            model_name='video_product',
            name='Buyers',
        ),
    ]
