# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-10-07 03:22
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_product_has_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='Awards',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='Bio',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
