# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-10-11 03:53
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_auto_20171007_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='Highlights',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='Awards',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='Bio',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
