# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-07 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0002_auto_20171007_1128'),
        ('User', '0007_auto_20171007_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='Following',
            field=models.ManyToManyField(default='', to='Instructors.Instructor'),
        ),
    ]
