# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-07 11:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_auto_20171007_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='Followers',
        ),
    ]
