# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-07 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_remove_instructor_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='Followers',
            field=models.ManyToManyField(default='', to='User.Athlete'),
        ),
    ]
