# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-07 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0016_course_item_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Price',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
    ]
