# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-07 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0018_remove_product_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Owner',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Products', to='User.Instructor'),
        ),
    ]
