# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-07 13:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0019_product_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Owner',
        ),
    ]
